### ISSUE TITLE
Adding instances to the list

### ISSUE THREAD

**Issue by Murazaki** [hachyderm/hack#3]
What should be the criteria for us adding instances ?

I've been checking some accounts, and I can see websites that could be in there that are not.
The issue is sometimes it can be really tricky to know what to block and what not to.

Should we make rules for it ?

**Comment by brazda** [comment]
So why is linuxrocks.online and fossdom in the list?

**Comment by Trinsec** [comment]
Why's qoto.org in there? It's a STEM instance full of scientists. In fact, I've never seen so many female scientists in one instance before since the latest Twixodus, let's not kick them out of the Fediverse.

**Comment by Murazaki** [comment]
Hey @brazda and @trinsec, and to anyone here : please state your reasons to keep or not keep, people will answer with there's, so we know why.

Just so you know, a lot of instances are already blocked in most of the fediverse for advocating "free speech", which most of the time meant to not block toxic behaviors, the kind of thing we can't afford when we want to protect people from harm.

**Comment by Trinsec** [comment]
Okay, qoto.org is an 'inclusive free speech instance'. It means it's not like those rightwing instances thinking that free speech means speaking bullshit without consequences. It means the correct use of 'free speech' as in that you're safe from suppression and won't be banned for having an unpopular opinion.

Our house rules in our About page contains this important line: We won’t censor unpopular ideas and statements and welcome people from across the political spectrum, but hate-based speech such as sexist, racist, or homophobic speech will not be tolerated, be kind to each other.

I have the feeling somebody just saw 'free speech' and immediately thought 'block' without actually asking what it means for this instance. Hate speech is *not* tolerated at Qoto.

Honest? I cordially invite you to check out our local timeline. A ridiculous amount is just science and technobabble. It's a place where geeks can nerd out.

**Comment by mitsuhiko** [comment]
I would be curious to learn why mastodon.cloud is on that list.

**Comment by krisnova** [comment]
Mastodon.cloud (and 4 others) have been removed from the blocklist, and opened up. It was an honest mistake for importing them from other servers. Myself and other moderators are trying hard to keep up with moderation so thanks for being patient with us while we inevitbly make mistakes while adopting a new social media responsibility over night.

As far as adding new instances is concerned feel free to open up issues or PRs with them (please supply reason and evidence if you believe it would be helpful for your cause) and if we determine they violate our rules/mission we will accept your contribution. We will use our best judgement here, and we believe in 2nd chances. So please keep issues coming if you have questions.
