### ISSUE TITLE
mastodon.cloud in the blocklist?

### ISSUE THREAD

**Issue by chx** [hachyderm/hack#4]
The blocklist contains mastodon.cloud I know nothing but Anil Dash is on mastodon.cloud so it seems strange to block it. Also, I boosted his tweet and it appeared just fine?

**Comment by krisnova** [comment]
A lot of these were imported from other instances when we first turned on hachyderm earlier this year. We have had to remove a handful of others.

Thanks for calling this out. 

https://github.com/hachyderm/hack/commit/45c85223e99ed91d0790510403dfb59f786ee73f
