### ISSUE TITLE
Remove qoto.org from list 

### ISSUE THREAD

**Issue by seachdamh** [hachyderm/hack#8]
It is really good STEM oriented instance with clear speach anti-hate rules. I really like content it have. I don't see reason why this instance should be blocked.

**Comment by tomchiverton** [comment]
+1 Qoto seems solid and well moderated

**Comment by SETIguy** [comment]
I have also had no problems with using qoto.org.

**Comment by mkitti** [comment]
Highlights from: https://qoto.org/about/more
* "Unpopular opinions are acceptable, explicit hate-speech is not."
* "We federate with all servers: we don’t block any servers."

**Comment by krisnova** [comment]
Removed. Thank you for forgiving out mistake.

**Comment by Jackenmen** [comment]
I happened to look at hachyderm.io's list of suspended servers and qoto.org appears to still be there. Is it because the list from here just hasn't been synced with the server yet or is there a different reason?

**Comment by freemo** [comment]
> Highlights from: https://qoto.org/about/more
> 
> * "Unpopular opinions are acceptable, explicit hate-speech is not."
> * "We federate with all servers: we don’t block any servers."

The first point of course I have no issue with.. having an unnpopular opinion will not and should not get you banned. If it did academic honesty would be impossible.

As for the second pointn, we do that specifically at the request of our LGBTQ community and for their physical safety, see this post for details: https://qoto.org/@freemo/109319817943835261

**Comment by mkitti** [comment]
I believe my quotes were direct at the time, but I would be happy to revise them if there is a need.

**Comment by freemo** [comment]
> I believe my quotes were direct at the time, but I would be happy to revise them if there is a need.

Can you point to where in the text that is? I think you were quoting an old version, and without context

**Comment by mkitti** [comment]
Yes, I believe it was an old version from 12 days ago. Again, I would be happy to revise it if it would help, but I think this specific issue is closed.
